# These are supported funding model platforms
# Fix my profile link https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: https://github.com/itzCozi
